package sanjeevni.gui;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevni.utility.PasswordEncryption;
import sanjeevniapp.dao.DoctorsDao;
import sanjeevniapp.dao.EmpDao;
import sanjeevniapp.dao.UserDao;
import sanjeevniapp.pojo.DoctorsPojo;
import sanjeevniapp.pojo.UserPojo2;

public class AddDoctor extends javax.swing.JFrame {

    private String selEmpId, selEmpName, emailId;
    private String contactNo, qualification, special;
    private String loginid ,pass1, pass2; 
    private Map<String, String> doclist;

    
    public AddDoctor() {
        initComponents();
        geneNewDocId(); 
        doclist= new HashMap<>(); 
        loadDocDetails();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtlogin = new javax.swing.JTextField();
        txtdocid = new javax.swing.JTextField();
        txtspecial = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtqual = new javax.swing.JTextField();
        txtdocname = new javax.swing.JTextField();
        combogender = new javax.swing.JComboBox<>();
        comboempid = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        pwd2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 251, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        txtdocid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdocid.setEnabled(false);
        txtdocid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocidActionPerformed(evt);
            }
        });
        jPanel2.add(txtdocid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 150, -1));

        txtspecial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, -1));

        txtcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 150, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 150, -1));

        txtqual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 150, -1));

        txtdocname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdocname.setEnabled(false);
        txtdocname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtdocname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, -1));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        combogender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenderActionPerformed(evt);
            }
        });
        jPanel2.add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 150, 30));

        comboempid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboempidActionPerformed(evt);
            }
        });
        jPanel2.add(comboempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 50, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Doctor ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Qualification");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Specialization");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Contact No.");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 80, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email ID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 60, 20));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setText("Employee ID");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 20));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setText("Doctor Name");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Login ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Password");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Retype Password");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 20));

        pwd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd1ActionPerformed(evt);
            }
        });
        jPanel2.add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));

        pwd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd2ActionPerformed(evt);
            }
        });
        jPanel2.add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 620, 260));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Sanjeevni Application ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 420, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -140, 960, 340));

        btnregister.setBackground(new java.awt.Color(0, 204, 204));
        btnregister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 150, 30));

        btnback.setBackground(new java.awt.Color(0, 204, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, 30));

        btnlogout.setBackground(new java.awt.Color(0, 204, 204));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/register Doctor.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 230, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd1ActionPerformed
  
    }//GEN-LAST:event_pwd1ActionPerformed

    private void txtdocidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocidActionPerformed
        
    }//GEN-LAST:event_txtdocidActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        JFrame nextframe = new ManageDoctors();
       nextframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void comboempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboempidActionPerformed
    if(comboempid.getSelectedItem()==null)
            return; 
     selEmpId = comboempid.getSelectedItem().toString();
    selEmpName = (String) doclist.get(selEmpId); 
    txtdocname.setText(selEmpName);
    }//GEN-LAST:event_comboempidActionPerformed

    private void txtdocnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocnameActionPerformed
     
    }//GEN-LAST:event_txtdocnameActionPerformed

    private void combogenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenderActionPerformed
        
    }//GEN-LAST:event_combogenderActionPerformed

    private void pwd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd2ActionPerformed
       
    }//GEN-LAST:event_pwd2ActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
         if (validateInputs()==false)
         {
             JOptionPane.showMessageDialog(null, "Please enter all fields");
         }
        String validpassword=matchpassword();
        if(validpassword!= null)
        {
            JOptionPane.showMessageDialog(null, validpassword);
            return;
        }
        if(validContact()==false)
        {
            JOptionPane.showMessageDialog(null,"Invalid Mobile Number");
        return; 
        }
        
        try
        {
            DoctorsPojo doc = new DoctorsPojo();     //set all details from the frame into doc pojo 
            doc.setDoctor_id(txtdocid.getText());
            doc.setDoctor_name(selEmpName); 
            doc.setEmail_id(emailId);
            doc.setGender(combogender.getSelectedItem().toString());
            doc.setContact_no(contactNo);
            doc.setQualification(qualification);
            doc.setSpecialist(special);
            
            UserPojo2 user = new UserPojo2();    //setting details from frame into user pojo 
            user.setLogin_id(loginid);
            user.setUser_name(selEmpName);
             String encpassword= new String(PasswordEncryption.getEncryptedPassword(pass1));
            user.setPassword(encpassword);
            user.setUser_type("DOCTOR");
           
            
            boolean result1= DoctorsDao.addDoc (doc); //storing results that whether the details are added in both tables or not
            boolean result2= UserDao.addUser (user); 
             if(result1==true && result2==true)
                     {
                         JOptionPane.showMessageDialog(null, "Details added successfully in both tables");
                         clearALL();
                         return; 
                     }
             JOptionPane.showMessageDialog(null, "Registration failed");
             return;
  
        }
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Error in DB" +ex);
           ex.printStackTrace();
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
JFrame obj = new LoginFrame(); 
obj.setVisible(true); 
this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> comboempid;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblname;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdocid;
    private javax.swing.JTextField txtdocname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtqual;
    private javax.swing.JTextField txtspecial;
    // End of variables declaration//GEN-END:variables

    
    private void loadDocDetails()
    {
        try{
            doclist=EmpDao.getUnregDocs();
            Set <String> empIDset = doclist.keySet();
            for(String empID : empIDset)
            {
                comboempid.addItem(empID);
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error in DB"+ex); 
            ex.printStackTrace();
        }
    }
    
    
    private boolean validateInputs() {
      loginid=txtlogin.getText().trim();
      char[] p1=pwd1.getPassword();
      char[] p2=pwd2.getPassword();
      contactNo=txtcontact.getText().trim();
      qualification=txtqual.getText().trim();
      emailId=txtemail.getText().trim();
     special=txtspecial.getText().trim();
      if(loginid.isEmpty() || p1.length==0 || p2.length==0 || contactNo.isEmpty() || qualification.isEmpty() || emailId.isEmpty() || special.isEmpty())
      {
          return false;
      }
      pass1=new String(p1);
      pass2=new String(p2);
      return true;
    }

    private boolean validContact() {
        char[] mob = contactNo.toCharArray(); 
        for(char ch : mob){
                if(Character.isDigit(ch)==false)
                    return false; 
        }
        if(contactNo.length()==10)
            return true; 
        return false; 
    }

    private String matchpassword() {
       pass1= pass1.trim();
       pass2= pass2.trim();
       if(pass1.length()<3 || pass2.length()<3)
       {
         return "Passwords must be of atleast 3 characters in length";
       }
         if(pass1.equals(pass2)==false)
     {
       return "Passwords do not match";
     }
       return null;
    }

    private void clearALL() {
      txtcontact.setText("");     
     txtdocid.setText("");
     txtemail.setText("");
     txtlogin.setText("");
     txtqual.setText("");
    txtspecial.setText("");
    pwd1.setText("");
    pwd2.setText("");
    doclist.remove(selEmpId);
    comboempid.removeItem(selEmpId);
    if(doclist.size()==0){
          JOptionPane.showMessageDialog(null,"All doctors registered!");
          ManageDoctors manageDoc=new ManageDoctors();
          manageDoc.setVisible(true);
          this.dispose();
    }
    }
    
    private void geneNewDocId(){
        try{
            String docID= DoctorsDao.getNewDocID();
            txtdocid.setText(docID);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error in DB"+ex);
            ex.printStackTrace();
        }
    }
}
