package sanjeevni.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevniapp.dao.EmpDao;
import sanjeevniapp.pojo.EmpPojo;

public class AddEmployee extends javax.swing.JFrame {

    private String emp_salary;
    private String emp_name;

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        generateNewId();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtempname = new javax.swing.JTextField();
        txtempsalary = new javax.swing.JTextField();
        txtempno = new javax.swing.JTextField();
        lblempname = new javax.swing.JLabel();
        lblsalary = new javax.swing.JLabel();
        lblempno = new javax.swing.JLabel();
        lblempjob = new javax.swing.JLabel();
        jcempjob = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(237, 251, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Employee Details"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setText("Back ");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 153, 153));
        btnadd.setText("Add Employee");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 140, 330, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(0, 153, 153));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 730, 10));
        jPanel3.add(txtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, 30));
        jPanel3.add(txtempsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 180, 30));

        txtempno.setEnabled(false);
        txtempno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempnoActionPerformed(evt);
            }
        });
        jPanel3.add(txtempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, 30));

        lblempname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempname.setText("Employee Name ");
        jPanel3.add(lblempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsalary.setText("Salary");
        jPanel3.add(lblsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        lblempno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempno.setText("Employee ID");
        jPanel3.add(lblempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblempjob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempjob.setText("Job");
        jPanel3.add(lblempjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, -1));

        jcempjob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Admin", "Doctor", "Receptionist" }));
        jPanel3.add(jcempjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 790, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Sanjeevni Application ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 746, 33));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/HomePageBG1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -90, 910, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
     
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void txtempnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempnoActionPerformed

    }//GEN-LAST:event_txtempnoActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        JFrame newframe = new ManageEmployees();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        boolean isInputValid = validateInputs();
        if (!isInputValid) {
            JOptionPane.showMessageDialog(null, "Please input all the data!");
            return;
        }
        try {
            double esal = Double.parseDouble(emp_salary);              //local me value parse karwa di 
            EmpPojo emp = new EmpPojo();                                           //object of EmpPojo
            emp.setEmp_id(txtempno.getText().trim());
            emp.setEmp_name(emp_name);
            emp.setEmp_salary(esal);
            emp.setEmp_department(jcempjob.getSelectedItem().toString());
            boolean result = EmpDao.addEmp(emp);             //via pojo obejct, dao method is called and answer stored in result
            if(result == true)
            {
                JOptionPane.showMessageDialog(null, "Record addedd successfully");
          generateNewId();                               //method for auto generating empID
          return;
            }
            JOptionPane.showMessageDialog(null, "Could not add the record! Try Again"); 
        } 
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error In DB"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
     catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please input numeric salary!"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcempjob;
    private javax.swing.JLabel lblempjob;
    private javax.swing.JLabel lblempname;
    private javax.swing.JLabel lblempno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtempno;
    private javax.swing.JTextField txtempsalary;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
        emp_name= txtempname.getText().trim();
        emp_salary= txtempsalary.getText().trim();
        if(emp_name.isEmpty() || emp_salary.isEmpty())
        {
            return false;
        }
        return true; 
    }

    private void generateNewId() {
       try{
           String empID =EmpDao.getNextEmpId();
           txtempno.setText(empID);
           txtempname.setText("");
           txtempsalary.setText("");
           jcempjob.setSelectedIndex(0);
        }
      catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error In DB"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
}
