package sanjeevni.gui;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevni.utility.UserProfile;
import sanjeevniapp.dao.EmpDao;
import sanjeevniapp.pojo.EmpPojo;

public class UpdateEmployee extends javax.swing.JFrame {

    private String empName;
    private String empSalary;


    public UpdateEmployee() {
        initComponents();
        setLocationRelativeTo(null);
        loadEmpID();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtempname = new javax.swing.JTextField();
        txtempsalary = new javax.swing.JTextField();
        lblempname = new javax.swing.JLabel();
        lblsalary = new javax.swing.JLabel();
        lblempno = new javax.swing.JLabel();
        lbldepartment = new javax.swing.JLabel();
        jcempjob = new javax.swing.JComboBox<>();
        jcempid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Sanjeevni Application ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 746, 33));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/HomePageBG1.jpg"))); // NOI18N
        jLabel2.setText("Home");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -150, 910, 530));

        btnhome.setForeground(new java.awt.Color(0, 204, 204));
        btnhome.setText("Home");
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(237, 251, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Employee"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(237, 251, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Employee Details"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setText("Back ");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 153, 153));
        btnupdate.setText("Update Employee");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 330, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(0, 153, 153));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 730, 20));
        jPanel3.add(txtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, 30));
        jPanel3.add(txtempsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 180, 30));

        lblempname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempname.setText("Employee Name ");
        jPanel3.add(lblempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsalary.setText("Salary");
        jPanel3.add(lblsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        lblempno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempno.setText("Employee ID");
        jPanel3.add(lblempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbldepartment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldepartment.setText("Department");
        jPanel3.add(lbldepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, -1));

        jcempjob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "DOCTOR", "RECEPTIONIST" }));
        jPanel3.add(jcempjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 30));

        jcempid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcempidActionPerformed(evt);
            }
        });
        jPanel3.add(jcempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 800, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        JFrame newframe = new ManageEmployees();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jcempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcempidActionPerformed
        //as soon as emp ID selected from combo, details should be displayed in txt fields 
        try {        
            String empid = jcempid.getSelectedItem().toString();
            EmpPojo emp = EmpDao.getEmployeeDetails(empid);            
            String emp_name = emp.getEmp_name();
            double emp_salary = emp.getEmp_salary();
            txtempname.setText(emp_name);
            txtempsalary.setText(String.valueOf(emp_salary));
            jcempjob.setSelectedItem(emp.getEmp_department().toUpperCase());
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "data cant be displayed");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jcempidActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
         if(validateInputs() ==false)
         {     
                 JOptionPane.showMessageDialog(null,"Input all fields");
                 return; 
             }
         else
         {
             try{
                 double esal= Double.parseDouble(empSalary);
                 EmpPojo emp = new EmpPojo();
                         emp.setEmp_salary(esal);
                         emp.setEmp_name(empName);
                         emp.setEmp_id(jcempid.getSelectedItem().toString());
                         emp.setEmp_department(jcempjob.getSelectedItem().toString());
                         boolean result = EmpDao.updateEmployee(emp); 
                         if(result)
                         {
                              JOptionPane.showMessageDialog(null,"Record updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                         if(UserProfile.getUserId().equalsIgnoreCase(emp.getEmp_id()))               //if the current user updates their own details
                         {
                             UserProfile.setUserName(empName);
                             return; 
                         }
             }
                JOptionPane.showMessageDialog(null,"Record not updated", "Failure", JOptionPane.INFORMATION_MESSAGE);
         }
         catch (SQLException ex){
                JOptionPane.showMessageDialog(null,"Error in DB "+ex.getMessage(),"Error",  JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
         }
         }
    
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
            });
                }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcempid;
    private javax.swing.JComboBox<String> jcempjob;
    private javax.swing.JLabel lbldepartment;
    private javax.swing.JLabel lblempname;
    private javax.swing.JLabel lblempno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtempsalary;
    // End of variables declaration//GEN-END:variables

    private void loadEmpID() {
        try {
            List<String> empIDList = EmpDao.getAllemployeeId();            //Dao se saari IDs ki list will be displayed in the combo
            //isme dao wali empidList aa rahi hai 
            for (String id : empIDList) {
                jcempid.addItem(id);
            }
}
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error In DB" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private boolean validateInputs() {
     empName= txtempname.getText().trim();
     empSalary= txtempsalary.getText().trim();
     if(empName.isEmpty() || empSalary.isEmpty())
     {
         return false;
    }
     return true; 
}
}
