package sanjeevni.gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevniapp.dao.ReceptionistDao;
import sanjeevniapp.pojo.ReceptionistPojo;

public class UpdateRecep extends javax.swing.JFrame {
 private Map<String,String> reclist; 
    private String selEmpId;
    private String selEmpName;
    private String loginid;
    private String pass1;
    private String pass2;
    private String selrecid;
    private String recname;
    public UpdateRecep() {
        initComponents();
        this.loadReceptionistId();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtlogin = new javax.swing.JTextField();
        txtrecepname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        pwd2 = new javax.swing.JPasswordField();
        combogender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcrecepID = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 251, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receptionist's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 380, -1));

        txtrecepname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtrecepname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecepnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtrecepname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 380, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Receptionist ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setText("Receptionist's Name");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Login ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Password");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Retype Password");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 110, 20));

        pwd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd1ActionPerformed(evt);
            }
        });
        jPanel2.add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));

        pwd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd2ActionPerformed(evt);
            }
        });
        jPanel2.add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 110, -1));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        combogender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenderActionPerformed(evt);
            }
        });
        jPanel2.add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 20));

        jcrecepID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcrecepIDActionPerformed(evt);
            }
        });
        jPanel2.add(jcrecepID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 380, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 640, 270));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Sanjeevni Application ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 420, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -140, 900, 340));

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 150, 170));

        btnupdate.setBackground(new java.awt.Color(0, 204, 204));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 150, 30));

        btnback.setBackground(new java.awt.Color(0, 204, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 60, 30));

        btnlogout.setBackground(new java.awt.Color(0, 204, 204));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrecepnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecepnameActionPerformed

    }//GEN-LAST:event_txtrecepnameActionPerformed

    private void pwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd1ActionPerformed

    }//GEN-LAST:event_pwd1ActionPerformed

    private void pwd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd2ActionPerformed

    }//GEN-LAST:event_pwd2ActionPerformed

    private void combogenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenderActionPerformed

    }//GEN-LAST:event_combogenderActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if (validateInputs()==false)
        {
            JOptionPane.showMessageDialog(null, "Please enter all fields");
        }
        String validpassword=matchpassword();
        if(validpassword!= null)
        {
            JOptionPane.showMessageDialog(null, validpassword);
            return;
        }

        try
        {
            ReceptionistPojo recep = new ReceptionistPojo();     //set all details from the frame into doc pojo
           // recep.setReceptionist_id(jcrecepID.getSelectedItem().toString());
            recep.setReceptionist_id(selrecid);
            recep.setReceptionist_name(recname);
            recep.setGender(combogender.getSelectedItem().toString());

            boolean result1= ReceptionistDao.addRecep (recep); //storing results that whether the details are added in  tables or not
            if(result1==true )
            {
                JOptionPane.showMessageDialog(null, "Details added successfully in receptionist table");
                clearALL();
                return;
            }
            JOptionPane.showMessageDialog(null, "Updation failed");
            return;

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error in DB" +ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        ManageRecep nextframe = new ManageRecep();
        nextframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jcrecepIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcrecepIDActionPerformed
        if(jcrecepID.getSelectedIndex()==-1){
            return;
        }
        selrecid = jcrecepID.getSelectedItem().toString();
        try{
            recname = ReceptionistDao.getRecName(selrecid);
        txtrecepname.setText(recname);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error in database " + ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jcrecepIDActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        JFrame obj = new LoginFrame();
        obj.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRecep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcrecepID;
    private javax.swing.JLabel lblname;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtrecepname;
    // End of variables declaration//GEN-END:variables

private void loadReceptionistId() {
        try{
            List<String>recepList=ReceptionistDao.getAllReceptionistId();
            for(String recId:recepList){
                jcrecepID.addItem(recId);
            } 
       }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in DB:"+ex);
            ex.printStackTrace();
        }
    }
private boolean validateInputs() {
      loginid=txtlogin.getText().trim();
      char[] p1=pwd1.getPassword();
      char[] p2=pwd2.getPassword();
      if(loginid.isEmpty() || p1.length==0 || p2.length==0)
      {
          return false;
      }
      pass1=new String(p1);
      pass2=new String(p2);
      return true;
    }

    private String matchpassword() {
      pass1= pass1.trim();
       pass2= pass2.trim();
       if(pass1.length()<3 || pass2.length()<3)
       {
         return "Passwords must be of atleast 3 characters in length";
       }
         if(pass1.equals(pass2)==false)
     {
       return "Passwords do not match";
     }
       return null;
    }

    private void clearALL() {
     //txtrecepid.setText("");
     txtlogin.setText("");
    pwd1.setText("");
    pwd2.setText("");
    reclist.remove(selEmpId);
   // comboempid.removeItem(selEmpId);
    if(reclist.size()==0){
          JOptionPane.showMessageDialog(null,"All receptionists registered!");
          ManageRecep manageRec=new ManageRecep();
          manageRec.setVisible(true);
          this.dispose();
    }
    }
    
}
