package sanjeevni.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevni.utility.OTPSender;
import sanjeevni.utility.SenderInterface;
import sanjeevniapp.dao.AppointmentDao;
import sanjeevniapp.dao.DoctorsDao;
import sanjeevniapp.dao.PatientDao;
import sanjeevniapp.pojo.AppointmentPojo;
import sanjeevniapp.pojo.PatientsPojo;

public class VerifyOtpFrame extends javax.swing.JFrame{

   PatientsPojo patient ;
   String contactNo2; 
   String docname; 
    private Double mobNo;
   
    public VerifyOtpFrame(PatientsPojo patient) {
     this();    //to initialize the components
     this.txtpatientname.setText(patient.getFirst_name()+ " "+ patient.getLast_name());
     this.patient= patient; 
    // this.contactNo2.setText(patient.getMob_no());
     //this.docname = docname;
       try {
           this.docname= DoctorsDao.getDocnamebyId(patient.getDoc_id());
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "DB Error");
          ex.printStackTrace();
       }   
    }
       
    public VerifyOtpFrame() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
     public VerifyOtpFrame(PatientsPojo patient, String docname)
{
       this(); 
       this.txtpatientname.setText(patient.getFirst_name()+" " +   patient.getLast_name());
       this.txtphone.setText(patient.getMob_no());
       this.patient = patient;
       this.docname = docname;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnverify = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtotp = new javax.swing.JTextField();
        lblempname = new javax.swing.JLabel();
        lblempno = new javax.swing.JLabel();
        EnterOTP = new javax.swing.JLabel();
        txtpatientname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        btnsendotp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Sanjeevni Application ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 746, 33));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevni/images/HomePageBG1.jpg"))); // NOI18N
        jLabel2.setText("Home");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -150, 910, 520));

        btnhome.setForeground(new java.awt.Color(0, 204, 204));
        btnhome.setText("Home");
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(237, 251, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Verfiy OTP"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(237, 251, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setText("Back ");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnverify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnverify.setForeground(new java.awt.Color(0, 153, 153));
        btnverify.setText("Verify");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        jPanel3.add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 330, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(0, 153, 153));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 730, 20));
        jPanel3.add(txtotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, 30));

        lblempname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempname.setText("Patient Name ");
        jPanel3.add(lblempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblempno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempno.setText("Phone no.");
        jPanel3.add(lblempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        EnterOTP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnterOTP.setText("Enter OTP");
        jPanel3.add(EnterOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, -1));

        txtpatientname.setEnabled(false);
        jPanel3.add(txtpatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, 30));

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel3.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, 30));

        btnsendotp.setText("SEND OTP");
        btnsendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendotpActionPerformed(evt);
            }
        });
        jPanel3.add(btnsendotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 260, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 800, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        JFrame newframe = new AddPatient();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        if(validateInputs() ==false)
        {
            JOptionPane.showMessageDialog(null,"Input all fields");
            return;
        }   
           // System.out.println(validOTP() + "verify");
            if(validOTP())
            {
            try      //if the otp is valid then add the details to the appointment table
            { 
                boolean result1= PatientDao.addPatient(patient); 
                System.out.println("xyz");
                AppointmentPojo appt= new AppointmentPojo();
                appt.setOpd(patient.getOpd());
                appt.setMob_no(patient.getMob_no());
                appt.setPat_id(patient.getPatient_id());
                appt.setDate_time(patient.getDate().toString());
                appt.setPat_name(txtpatientname.getText().trim());
                appt.setStatus("REQUEST");
                appt.setDoc_name(docname);
                System.out.println("abc");
                boolean result2= AppointmentDao.addAppointment(appt); 
                System.out.println("sdinjeoiwv ");
                
                if(result1 && result2)
                {
                    System.out.println("done");
                    JOptionPane.showMessageDialog(null, "Records entered successfully");
                    JFrame op = new AddPatient();
                    this.dispose();
                    op.setVisible(true); 
                }     
            }
             catch(SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, "Error in DB " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } 
            finally {
                return;
                        }    
            }
    }//GEN-LAST:event_btnverifyActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendotpActionPerformed
       if(this.validContact()==false)
       {
           JOptionPane.showMessageDialog(null, "Enter valid contact number");
       }
       else
       {
           try{
            SenderInterface sender = new OTPSender();
            String potp = String.valueOf(patient.getOtp());
            boolean result = sender.send(patient.getMob_no(),potp);
            if(result){
                JOptionPane.showMessageDialog(null,"OTP sent successfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Cannot send OTP. Please check the number!");
            }
            }
               catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Server issue");
           ex.printStackTrace();
        }
       }
    }//GEN-LAST:event_btnsendotpActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
            
    }//GEN-LAST:event_txtphoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyOtpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterOTP;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsendotp;
    private javax.swing.JButton btnverify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblempname;
    private javax.swing.JLabel lblempno;
    private javax.swing.JTextField txtotp;
    private javax.swing.JTextField txtpatientname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
      if(txtotp.getText().isEmpty()==false && validContact()==true)
      {
          return true; 
      }
      return false; 
    }
    
     private boolean validContact() {
         try{
           mobNo = Double.parseDouble(this.txtphone.getText().trim());
           int digits = (int)(Math.log10(mobNo)+1);
            System.out.println(digits);
            if(digits !=10){
                
                return false;
            }
           patient.setMob_no(txtphone.getText().trim());
           return true;
       }
       catch(NumberFormatException ex){
           ex.printStackTrace();
           return false;
       }
     }
    private boolean validOTP() {
        boolean result = false;
        try{
            int otp =0; 
             otp = Integer.parseInt(txtotp.getText().trim());
            if(otp == patient.getOtp())
            {
                result = true;         
                   System.out.println("true try");
       return result; 
            }
                else
            {
                System.out.println("false try");
            }
        
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please enter valid otp!");
        }
        finally{
            System.out.println(result + "finally");
            return result;
            
            
        }
       
    }
}


